wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.30
    code_path: code/main_ac_mcc.py
    docker_digest: sha256:d332e7792d7078fbd56a27797ccd6deb9742943c0ff907b7335c6f4086c0f167
    docker_image: agkhalil/pls
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 50
episodes:
  desc: null
  value: 10000
gamma:
  desc: null
  value: 0.99
lr_ac:
  desc: null
  value: 0.0001
lr_cr:
  desc: null
  value: 1.0e-06
seed:
  desc: null
  value: 42
