wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.30
    code_path: code/main_ac_mcc.py
    docker_digest: sha256:e06def8bbc5226ceb0e0f28c5e0ccfecd1d38216b0d01eb5f49e6d26b7705ae2
    docker_image: agkhalil/pls
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
