wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.30
    code_path: code/dqn.py
    docker_digest: sha256:e06def8bbc5226ceb0e0f28c5e0ccfecd1d38216b0d01eb5f49e6d26b7705ae2
    docker_image: agkhalil/pls
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 64
episodes:
  desc: null
  value: 10000
eps_decay:
  desc: null
  value: 0.999
eps_end:
  desc: null
  value: 0.05
eps_start:
  desc: null
  value: 0.9
epsilon:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.9
lr:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 42
update_target:
  desc: null
  value: 500
