wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.22
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 50
episodes:
  desc: null
  value: 10000
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.0005
seed:
  desc: null
  value: 42
